name: pkgx/dev
description:
  runs `pkgx`’s `dev` tool making the resulting packages available to this job

inputs:
  path:
    required: false

runs:
  using: composite
  steps:
    - uses: pkgxdev/setup@v4

    - run: |
        TMP="$(mktemp)"
        "$GITHUB_ACTION_PATH"/app.ts "$PWD" > "$TMP"
        echo "file=$TMP" >> $GITHUB_OUTPUT
      id: env
      working-directory: ${{ inputs.path }}
      shell: bash

    - run: |
        if ! node --version >/dev/null 2>&1; then
          set -a
          eval "$(pkgx +node)"
          set +a
        fi
        node "$GITHUB_ACTION_PATH"/action.js ${{ steps.env.outputs.file }}
      shell: bash
