name: pkgx/dev
description:
  runs `pkgx`’s `dev` tool making the resulting packages available to this job

inputs:
  path:
    required: false

runs:
  using: composite
  steps:
    - uses: pkgxdev/setup@v1

    - run: |
        if [ -n "${{ inputs.path }}" ]; then
          cd "${{ inputs.path }}"
        fi
        pkgx --internal.activate "$PWD" > file
        node parse.js
      shell: bash
