name: pkgx/dev
description:
  runs `pkgx`’s `dev` tool making the resulting packages available to this job

inputs:
  path:
    required: false

runs:
  using: composite
  steps:
    - uses: pkgxdev/setup@v2

    - run: |
        if [ -n "${{ inputs.path }}" ]; then
          cd "${{ inputs.path }}"
        fi
        pkgx --internal.activate "$PWD" > file
        if ! command -v node >/dev/null 2>&1; then
          eval "$(pkgx +node)"
        fi
        node $GITHUB_ACTION_PATH/parse.js
      shell: bash
