name: pkgx/dev
description:
  runs `pkgx`’s `dev` tool making the resulting packages available to this job

inputs:
  path:
    required: false

runs:
  using: composite
  steps:
    - uses: pkgxdev/setup@v2

    - run: |
        TMP="$(mktemp)"
        pkgx --internal.activate "$PWD" > "$TMP"
        echo "file=$TMP" >> $GITHUB_OUTPUT
      id: env
      working-directory: ${{ inputs.path }}
      shell: bash

    # github can not be relied on apparently to provide a working node…
    - run: |
        if ! node --version >/dev/null 2>&1; then
          eval "$(pkgx +node)"
        fi
      shell: bash

    - run: node "$GITHUB_ACTION_PATH"/parse.js ${{ steps.env.outputs.file }}
      shell: bash
