on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container:
          - null
          - ubuntu
    container: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo '{}' > package.json
          echo '{}' > deno.json
      - uses: ./
      - run: echo $PATH
      - run: env
      - run: deno --version
