on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container:
          - null
        #  - ubuntu FIXME pkgx node fails to load with missing libcrypto.1.1.dylib
    container: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v4
      - run: echo '{}' > deno.json
      - uses: ./
      - run: echo $PATH
      - run: env
      - run: deno --version
