on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-action:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container:
          - null
        #  - ubuntu FIXME pkgx node fails to load with missing libcrypto.1.1.dylib
    container: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v4
        with:
          path: clone
      - run: echo '{}' > deno.json
      - run: "! deno"
      - uses: ./clone
      - run: echo $PATH
      - run: env
      - run: deno --version

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denolib/setup-deno@v2
        with:
          deno-version: v2.x
      - run: deno fmt --check .
      - run: deno lint .
      - run: deno check ./app.ts
